name: Local
variables:
  - name: token
    value: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNWM1OWJlMC0wYTdiLTQ4ZjEtYTM3Yy02NDc2NGY4ODExN2MiLCJ0ZW5hbnRJZCI6IjZhZmQwN2U1LTJkNjMtNGY3MC04NjM3LTAyOGFhNGNjNDk3MSIsInJvbGVJZCI6IjdjYzNmOWRmLTM3YTktNDEyOC1iNTNlLTdhMDAyZjdiNzg1OCIsInJvbGVDb2RlIjoiT1dORVIiLCJzdG9yZUlkIjpudWxsLCJlbWFpbCI6Im93bmVyQGRlbW8uY29tIiwiaWF0IjoxNzg1OTMxODczLCJleHAiOjE3ODU5MzI3NzN9.EfBC4ffvODMZlGy27yGXTXybPy0wovNQYzsXAUhHovI
